export const columnsProduct = [
    { name: "ID", uid: "id", sortable: true },
    { name: "PRODUIT", uid: "name", sortable: true },
    { name: "PRIX", uid: "price", sortable: true },
    { name: "CATÉGORIE", uid: "category", sortable: true },
    { name: "STOCK", uid: "stock" },
    { name: "FOURNISSEUR", uid: "supplier" },
    { name: "STATUS", uid: "status", sortable: true },
    { name: "ACTIONS", uid: "actions" },
];

export const columnsCommande = [
    { name: "NUMÉRO", uid: "commande_number", sortable: true },
    { name: "CLIENT", uid: "client_id", sortable: true },
    { name: "RESTE À PAYER", uid: "commande_rest_to_pay", sortable: true },
    { name: "STATUS", uid: "status_id", sortable: true },
    { name: "FACTURE", uid: "facture_id", sortable: true },
    { name: "DATE", uid: "created_at", sortable: true },
    { name: "ACTIONS", uid: "actions" },
];

export const statusOptionsProduct = [
    { name: "En stock", uid: "en_stock" },
    { name: "Stock épuisé", uid: "stock_epuise" },
    { name: "Livraison en cours", uid: "livraison_en_cours" },
    { name: "Livrée", uid: "livree" },
    { name: "En attente de livraison", uid: "en_attente_livraison" },
    { name: "En commande", uid: "en_commande" },
    { name: "Livraison annulée", uid: "livraison_annulee" },
    { name: "Commande annulée", uid: "commande_annulee" },
];

export const products = [
    {
        id: 1,
        name: "iPhone 15 Pro",
        price: "1229.00",
        category: "Smartphones",
        status: "en_stock",
        stock: "45",
        avatar: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=150",
        supplier: "Apple Inc.",
    },
    {
        id: 2,
        name: "MacBook Air M2",
        price: "1199.00",
        category: "Ordinateurs",
        status: "livraison_en_cours",
        stock: "12",
        avatar: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=150",
        supplier: "Apple Inc.",
    },
    {
        id: 3,
        name: "Samsung Galaxy S24",
        price: "899.00",
        category: "Smartphones",
        status: "en_stock",
        stock: "28",
        avatar: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=150",
        supplier: "Samsung Electronics",
    },
    {
        id: 4,
        name: "Sony WH-1000XM5",
        price: "399.00",
        category: "Audio",
        status: "stock_epuise",
        stock: "0",
        avatar: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=150",
        supplier: "Sony Corporation",
    },
    {
        id: 5,
        name: "Dell XPS 13",
        price: "1099.00",
        category: "Ordinateurs",
        status: "en_attente_livraison",
        stock: "8",
        avatar: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=150",
        supplier: "Dell Technologies",
    },
    {
        id: 6,
        name: "Nintendo Switch OLED",
        price: "349.00",
        category: "Gaming",
        stock: "22",
        avatar: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=150",
        supplier: "Nintendo Co.",
        status: "en_stock",
    },
    {
        id: 7,
        name: "AirPods Pro 2",
        price: "279.00",
        category: "Audio",
        status: "livree",
        stock: "35",
        avatar: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=150",
        supplier: "Apple Inc.",
    },
    {
        id: 8,
        name: "iPad Pro 12.9\"",
        price: "1199.00",
        category: "Tablettes",
        status: "en_commande",
        stock: "15",
        avatar: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=150",
        supplier: "Apple Inc.",
    },
    {
        id: 9,
        name: "LG OLED 55\"",
        price: "1499.00",
        category: "TV & Écrans",
        status: "livraison_annulee",
        stock: "3",
        avatar: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=150",
        supplier: "LG Electronics",
    },
    {
        id: 10,
        name: "Canon EOS R5",
        price: "3899.00",
        category: "Photo",
        status: "en_stock",
        stock: "7",
        avatar: "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=150",
        supplier: "Canon Inc.",
    },
    {
        id: 11,
        name: "Microsoft Surface Pro 9",
        price: "1099.00",
        category: "Tablettes",
        status: "en_stock",
        stock: "18",
        avatar: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=150",
        supplier: "Microsoft Corporation",
    },
    {
        id: 12,
        name: "Bose QuietComfort 45",
        price: "329.00",
        category: "Audio",
        status: "commande_annulee",
        stock: "0",
        avatar: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=150",
        supplier: "Bose Corporation",
    },
    {
        id: 13,
        name: "Google Pixel 8 Pro",
        price: "999.00",
        category: "Smartphones",
        status: "en_stock",
        stock: "24",
        avatar: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=150",
        supplier: "Google LLC",
    },
    {
        id: 14,
        name: "Tesla Model Y Accessoires",
        price: "299.00",
        category: "Automobile",
        status: "en_attente_livraison",
        stock: "12",
        avatar: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=150",
        supplier: "Tesla Inc.",
    },
    {
        id: 15,
        name: "Dyson V15 Detect",
        price: "749.00",
        category: "Électroménager",
        status: "livraison_en_cours",
        stock: "9",
        avatar: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150",
        supplier: "Dyson Ltd.",
    },
    {
        id: 16,
        name: "Apple Watch Series 9",
        price: "429.00",
        category: "Montres connectées",
        status: "en_stock",
        stock: "31",
        avatar: "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=150",
        supplier: "Apple Inc.",
    },
    {
        id: 17,
        name: "HP Envy x360",
        price: "899.00",
        category: "Ordinateurs",
        status: "stock_epuise",
        stock: "0",
        avatar: "https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=150",
        supplier: "HP Inc.",
    },
    {
        id: 18,
        name: "Logitech MX Master 3S",
        price: "99.00",
        category: "Accessoires",
        status: "livree",
        stock: "67",
        avatar: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=150",
        supplier: "Logitech International",
    },
    {
        id: 19,
        name: "Samsung 32\" Odyssey G7",
        price: "649.00",
        category: "Gaming",
        status: "en_commande",
        stock: "14",
        avatar: "https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=150",
        supplier: "Samsung Electronics",
    },
    {
        id: 20,
        name: "Kindle Paperwhite",
        price: "139.00",
        category: "Livres électroniques",
        status: "en_stock",
        stock: "42",
        avatar: "https://images.unsplash.com/photo-1481887328591-3e277f9473dc?w=150",
        supplier: "Amazon.com Inc.",
    },
];

export const statusOptionsCommande = [
    { name: "En attente", uid: "en_attente" },
    { name: "Confirmée", uid: "confirmee" },
    { name: "En préparation", uid: "en_preparation" },
    { name: "Expédiée", uid: "expediee" },
    { name: "Livrée", uid: "livree" },
    { name: "Annulée", uid: "annulee" },
];

export const INITIAL_VISIBLE_COLUMNS = ["name", "price", "category", "status", "actions"];
export const INITIAL_VISIBLE_COLUMNS_COMMANDE =
    ["commande_number",
        "commande_product_name",
        "commande_product_price",
        "status_id",
        "facture_id",
        "created_at",
        "actions",
        "client_id",
        "commande_rest_to_pay"
    ];